{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cicd-pipeline.fullname" . }}
  labels:
    {{- include "cicd-pipeline.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "cicd-pipeline.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- range .Values.networkPolicy.ingress.from }}
        - {{- toYaml . | nindent 10 }}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
        {{- if .Values.monitoring.enabled }}
        - protocol: TCP
          port: {{ .Values.monitoring.port }}
        {{- end }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow database connections
    - to:
        {{- range .Values.networkPolicy.egress.database }}
        - {{- toYaml . | nindent 10 }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 5432
    # Allow Redis connections
    - to:
        {{- range .Values.networkPolicy.egress.redis }}
        - {{- toYaml . | nindent 10 }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 6379
    # Allow HTTPS for external API calls
    - to: []
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
{{- end }}
