apiVersion: v1
kind: Service
metadata:
  name: {{ include "cicd-pipeline.fullname" . }}
  labels:
    {{- include "cicd-pipeline.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cicd-pipeline.selectorLabels" . | nindent 4 }}
---
{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cicd-pipeline.fullname" . }}-metrics
  labels:
    {{- include "cicd-pipeline.labels" . | nindent 4 }}
    component: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.monitoring.port }}"
    prometheus.io/path: "{{ .Values.monitoring.path }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.monitoring.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "cicd-pipeline.selectorLabels" . | nindent 4 }}
{{- end }}
