apiVersion: v1
kind: Namespace
metadata:
  name: cicd-pipeline
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: cicd-pipeline
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: TEST_ENV
          value: "minikube-test"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: cicd-pipeline
  labels:
    app: test-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: test-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
  namespace: cicd-pipeline
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>CI/CD Pipeline Test</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; }
            .status { color: green; font-weight: bold; }
            .container { max-width: 600px; margin: 0 auto; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🚀 CI/CD Pipeline Test Application</h1>
            <p class="status">✅ Service is running successfully!</p>
            <p>This is a test deployment to verify your Minikube setup.</p>
            <ul>
                <li><strong>Namespace:</strong> cicd-pipeline</li>
                <li><strong>Service:</strong> test-service</li>
                <li><strong>Port:</strong> 30080</li>
                <li><strong>Status:</strong> Healthy</li>
            </ul>
            <p>🎉 Your Minikube CI/CD environment is working correctly!</p>
        </div>
    </body>
    </html>
